### ISSUE TITLE
Question about model types and likelihood components

### ISSUE THREAD

**Issue by ramiromagno** [MurrayEfford/openCR#10]
Hi Murray,

I'm trying to get a comprehensive overview of the different model types and their likelihood components. Is there any place in the documentation where we have a table analogous to the one below but supplemented with the indication of which components are taken into account in each model type?

Many thanks in advance!

| is_spatial | code | type        |
| ---------- | ---- | ----------- |
| FALSE      | 1    | CJS         |
| FALSE      | 2    | JSSAb       |
| FALSE      | 3    | JSSAl       |
| FALSE      | 4    | JSSAf       |
| FALSE      | 5    | CJSmte      |
| TRUE       | 6    | CJSsecr     |
| TRUE       | 7    | JSSAsecrf   |
| TRUE       | 8    | JSSAsecrD   |
| TRUE       | 9    | JSSAsecrfCL |
| TRUE       | 9    | PLBsecrf    |
| TRUE       | 10   | JSSAsecrlCL |
| TRUE       | 10   | PLBsecrl    |
| TRUE       | 11   | JSSAsecrbCL |
| TRUE       | 11   | PLBsecrb    |
| TRUE       | 12   | JSSAsecrl   |
| TRUE       | 13   | JSSAsecrb   |
| TRUE       | 14   | JSSAsecrB   |
| FALSE      | 15   | JSSAfCL     |
| FALSE      | 15   | PLBf        |
| FALSE      | 16   | JSSAlCL     |
| FALSE      | 16   | PLBl        |
| FALSE      | 17   | JSSAbCL     |
| FALSE      | 17   | PLBb        |
| FALSE      | 18   | JSSAB       |
| FALSE      | 19   | JSSAN       |
| FALSE      | 20   | **Pradel**      |
| FALSE      | 21   | JSSARET     |
| FALSE      | 22   | JSSAg       |
| FALSE      | 23   | JSSAgCL     |
| FALSE      | 23   | PLBg        |
| TRUE       | 24   | JSSAsecrg   |
| TRUE       | 25   | JSSAsecrgCL |
| TRUE       | 25   | PLBsecrg    |
| FALSE      | 26   | **Pradelg**     |
| FALSE      | 27   | JSSAfgCL    |
| FALSE      | 28   | JSSAk       |
| FALSE      | 29   | JSSAkCL     |
| FALSE      | 29   | PLBk        |
| TRUE       | 30   | secrCL      |
| TRUE       | 31   | secrD       |

**Comment by MurrayEfford** [comment]
openCR model types are documented in section 5 of the vignette e.g. https://www.otago.ac.nz/density/pdfs/openCR-vignette.pdf (apologies for some formatting problems with the table column headings).
The numeric codes are strictly for internal use only. They can be got with the internal function typecode e.g., openCR:::typecode("CJS").

**Comment by ramiromagno** [comment]
Thank you so much, I will read it carefully.
