### ISSUE TITLE
Question about the `capthist` class and `dipperCH` data set

### ISSUE THREAD

**Issue by ramiromagno** [MurrayEfford/openCR#7]
Hi Murray,

Thanks for putting together this package!

I am trying to follow the vignette step by step, and stumbled on these first doubts.

The secr's documentation on the capthist classed objects indicates that `traps` and `session` are the two required attributes of a `capthist` object. It seems however that the `dipperCH` data set from the `{openCR}` package (a `capthist` object) does not contain any of those two attributes. Is this inconsistency an issue with the documentation of `capthist` class or with the way `dipperCH` has been constructed?

Also, I am a bit confused with the usage of the concepts session and occasion. From the help page on `caphist`:

> A capthist is primarily an array of values with dim(capthist) = c(nc, noccasions, ntraps) where nc is the number of detected individuals. Values maybe binary ({–1, 0, 1}) or integer depending on the detector type.

it seems that the second dimension of an  `capthist` object should refer to occasions. The `dipperCH` has 7 elements in the second dimension, which seems to refer to the different years. So in this case, years are occasions. So, shouldn't the attribute `sessionlabels` be more appropriately named `occasionlabels`?

``` r
library(openCR)
#> Loading required package: secr
#> This is secr 4.6.6. For overview type ?secr
#> This is openCR 2.2.6 pre-release. For overview type ?openCR and see openCR-vignette.pdf
attributes(openCR::dipperCH) |> names()
#> [1] "dim"           "class"         "covariates"    "intervals"    
#> [5] "sessionlabels"
```

<sup>Created on 2024-05-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by MurrayEfford** [comment]
These are reasonable questions.

openCR built on the structure of secr that was established much earlier. The scope of openCR was extended to include non-spatial models for which there is no spatial sampling and hence no need for a 'traps' component or a third dimension in the capthist object. This required some ad hoc changes to (simplification of) the definition of a capthist object for non-spatial data, as you have noticed. Note to self: The documentation of the capthist class should be tweaked to cover this, but without implying that secr itself uses non-spatial data.

Whereas secr has occasions nested within sessions, openCR uses a flat 'joined' structure that can accommodate 'robust design' data (multiple occasions per session). Breaks between consecutive sessions are indicated by a non-zero interval value. Nevertheless, from a user's point of view sessions still exist and need to be named in output. The dipper data have a single occasion per session, hence the two are not distinguishable.

Murray

**Comment by ramiromagno** [comment]
That makes sense, thanks!
